name: Call Azure DevOps Template

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
        default: 'Payel'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      # Step 2: Set up Azure DevOps credentials using the GitHub PAT
      - name: Set up Azure DevOps credentials
        run: |
          # Store Azure DevOps credentials in a temporary credentials file
          echo "https://:${{ secrets.AZURE_DEVOPS_TOKEN }}@dev.azure.com" > ~/.git-credentials
          git config --global credential.helper store

      # Step 3: Debug - Test PAT access to Azure DevOps
      - name: Test PAT access to Azure DevOps
        run: |
          curl -u :${{ secrets.AZURE_DEVOPS_TOKEN }} \
            https://dev.azure.com/senarindam/Payel%20Bose/_apis/git/repositories/Jfrog

      # Step 4: Clone the Azure DevOps repository containing the template
      - name: Clone Azure DevOps repository containing template
        run: |
          # Define the Azure DevOps repository URL with the PAT directly in the URL
          AZURE_DEVOPS_URL="https://${{ secrets.AZURE_DEVOPS_TOKEN }}@dev.azure.com/senarindam/Payel%20Bose/_git/Jfrog"
          
          # Clone the Azure DevOps repository securely
          git clone $AZURE_DEVOPS_URL

      # Step 5: Navigate to the directory where the template is stored and run it
      - name: Execute template from Azure DevOps repository
        run: |
          # Change directory to where the template is located (adjust path if needed)
          cd Jfrog/.github/workflows
          
          # Print name using the template
          echo "Running the 'Print My Name' template from Azure DevOps"
          
          # Execute the template (this should match the template's behavior)
          echo "Hello, my name is ${{ github.event.inputs.username }}"
