name: Call Azure DevOps Template

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
        default: 'Payel'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository (your main pipeline)
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      # Step 2: Set up Azure DevOps credentials (using the GitHub PAT stored in secrets)
      - name: Set up Azure DevOps credentials
        run: |
          # Store Azure DevOps credentials (use the GitHub PAT stored in secrets)
          echo "https://:${{ secrets.AZURE_DEVOPS_TOKEN }}@dev.azure.com" > ~/.git-credentials
          git config --global credential.helper store

      # Step 3: Clone the Azure DevOps repository containing the template
      - name: Clone Azure DevOps repository containing template
        run: |
          # Define the Azure DevOps repository URL
          AZURE_DEVOPS_URL="https://dev.azure.com/senarindam/Payel%20Bose/_git/Jfrog"
          
          # Clone the Azure DevOps repository
          git clone $AZURE_DEVOPS_URL

      # Step 4: Navigate to the directory where the template is stored and run it
      - name: Execute template from Azure DevOps repository
        run: |
          # Change directory to where the template is located (adjust path if needed)
          cd Jfrog/.github/workflows
          
          # Print name using the template
          echo "Running the 'Print My Name' template from Azure DevOps"
          
          # Execute the template (this should match the template's behavior)
          echo "Hello, my name is ${{ github.event.inputs.username }}"
