name: Call Azure DevOps Template

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
        default: 'Payel'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      # Step 2: Set up Azure DevOps credentials using the GitHub PAT
      - name: Set up Azure DevOps credentials
        run: |
          # Store Azure DevOps credentials in a temporary credentials file
          echo "https://:${{ secrets.AZURE_DEVOPS_TOKEN }}@dev.azure.com" > ~/.git-credentials
          git config --global credential.helper store

      # Step 3: Clone the Azure DevOps repository containing template
      - name: Clone Azure DevOps repository containing template
        run: |
          # Define the Azure DevOps repository URL with the PAT directly in the URL
          AZURE_DEVOPS_URL="https://${{ secrets.AZURE_DEVOPS_TOKEN }}@dev.azure.com/senarindam/Payel%20Bose/_git/Jfrog"
          
          # Clone the Azure DevOps repository securely
          git clone $AZURE_DEVOPS_URL

      # Step 4: Debug - Check if the repository has been cloned correctly
      - name: List files in the current directory
        run: |
          echo "Current directory contents:"
          ls -R

      # Step 5: Verify if the Jfrog directory exists
      - name: Verify Jfrog repository exists
        run: |
          if [ -d "Jfrog" ]; then
            echo "Jfrog directory exists."
            ls -R Jfrog
          else
            echo "Jfrog directory does not exist."
          fi

      # Step 6: Navigate to the directory where the template is located and run it
      - name: Execute template from Azure DevOps repository
        run: |
          # Check if the Jfrog directory exists
          if [ -d "Jfrog/.github/workflows" ]; then
            cd Jfrog/.github/workflows
            echo "Running the 'Print My Name' template from Azure DevOps"
            # Execute the template (this should match the template's behavior)
            echo "Hello, my name is ${{ github.event.inputs.username }}"
          else
            echo "Error: .github/workflows directory not found in Jfrog repository."
          fi
