name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
        default: 'Payel'

jobs:
  call-template:
    uses: ./.github/workflows/name.yml
    with:
      username: ${{ github.event.inputs.username }}
