name: Print My Name

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Say My Name
        run: echo "Hello, my name is ${{ inputs.username }}"
